#!/usr/bin/env ruby

require "promenade"
require "rack"
require "rackup"
require "prometheus/client/rack/exporter"

Promenade.setup

app = Rack::Builder.app do
  use Rack::Deflater
  use Prometheus::Client::Rack::Exporter
  map "/health" do
    run lambda { |_env| [200, { "Content-Type" => "text/plain" }, ["OK"]] }
  end
  run ->(_env) { [404, {}, ["visit /metrics for metrics"]] }
end

Signal.trap("TERM") { Rackup::Handler::WEBrick.shutdown }

Rackup::Handler::WEBrick.run app, Port: ENV.fetch("PORT", "9394"), Host: "0.0.0.0"
